### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by Niklp09** [Niklp09/chatplus#1]
- [x] add some translations
- [x] add command descriptions
- [x] remove the "moderator" chat
- [x] add sounds
